### ISSUE TITLE
Traceback from site: 'HTTP 403: Forbidden'

### ISSUE THREAD

**Issue by asmeurer** [pelson/repohealth.info#11]
Hi,

I was looking at /report/sympy/sympy on repohealth.info and got the following traceback:

```
Traceback (most recent call last):
  File "/app/repohealth/generate.py", line 63, in no_raise
    yield
  File "/app/repohealth/generate.py", line 200, in repo_data
    issues = loop.run_sync(issues_fn)
  File "/app/.conda/lib/python3.5/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/app/.conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/repohealth/github/issues.py", line 54, in repo_issues
    yield future
  File "/app/.conda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/app/.conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

Thanks,

**Comment by pelson** [comment]
Thanks @asmeurer. 

I suspect it is down to the high number of issues on the tracker. It looks like it is hitting ```https://api.github.com/repos/sympy/sympy/issues?page=...&per_page=100&state=all``` and failing for some reason. I intend to factor out the retry that was done in https://github.com/pelson/repo-health-report/blob/master/repohealth/github/stargazers.py#L75-L96 so that we can build a bit more resilience on this front. I'll need to do a similar activity to get a timeseries of "fork" data anyway, so will take a crack at it in the next week or so.

**Comment by pelson** [comment]
Similar issue just been seen on pandas-dev/pandas.

**Comment by asmeurer** [comment]
Don't know if it matters but there is a range of issues that are not taken due to an import ([example](https://github.com/sympy/sympy/issues/3040)).

**Comment by pelson** [comment]
Was that a typo? Issue 3040 raises a 404 for me...

**Comment by asmeurer** [comment]
That's the point.

**Comment by pelson** [comment]
Ah, ok. Thanks @asmeurer. 😄 
I have just deployed #13 and the report has come through at https://repohealth.info/report/sympy/sympy.

**Comment by pelson** [comment]
Interestingly, sympy looks like it has a commit from March 2000!?

**Comment by asmeurer** [comment]
Ha. git commit dates are lies. The earliest git commit is an svn import from 2007.

**Comment by pelson** [comment]
Just wanted to say I've rolled back from this change as it was having a knock on effect relating to issue caching. I'll take another look at addressing this once I get back to my machine in a few days.

**Comment by pelson** [comment]
Turned out I hadn't read the docs properly for one of the async fetch requests. Should all be up and running again with the required fix.
