### ISSUE TITLE
Redirect_uri doesn't match the registered callback URL

### ISSUE THREAD

**Issue by willelson** [pelson/repohealth.info#6]
After entering a GitHub repo (e.g. matplotlib/matplotlib) and submitting the form we get the following message:

"The redirect_uri MUST match the registered callback URL for this application.
https://repo-health-report.herokuapp.com/oauth?next=https%3A%2F%2Frepo-health-report.herokuapp.com%2F"

**Comment by pelson** [comment]
Thanks @willelson. I was having a few issues with my DNS at the time, should now be fixed from repohealth.info. Could you double check & if so, close the issue.

Thanks!
